### ISSUE TITLE
PMSM sinusoidal Inverter

### ISSUE THREAD

**Issue by sjdaliyan** [Captain-Pumpkinhead/PDM-DAC#1]
Greetings. can this code be used as a base for developing a sinusoidal 3-phase bldc inverter? goal is to reach foc control with rp2040 without help of arduino based solutions like simplefoc

**Comment by Captain-Pumpkinhead** [comment]
Yes, easily.

Your target lines for modification will be 87-111.  Triplicate `wave_position` so that there are three `wave_position` variables and add 2pi/3 and 4pi/3 respectively to `i1`.  Triplicate the `PDM Output` section.  Instead of using 3-4 output pins for more current like I did, it's probably smarter to connect the pin to base pin of a transistor.
